##################################################################################
# Automations for plants
##################################################################################


##################################################################################
# Switch
##################################################################################
# Switches are now under RFXTRX in config.yaml
#switch:
#- platform: rfxtrx
#  devices:
#    '0b11000001b521f603010f60':      # Nexa-plugg, knapp 3
#      name: plant_light
#    '0b11000101b510f603010f60':      # Nexa-plugg, knapp 3, 
#      name: plant_heatbed


##################################################################################
# Sensors
##################################################################################


##################################################################################
# Variables 
##################################################################################
input_select:
  heatbed_delay:
    name: Värmetid (av 15 min)
    options:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14

##################################################################################
# Automations 
##################################################################################
automation:
- id: 'automation_plantlights_on'
  alias: PlantLightsOn
  initial_state: true
  trigger:
    platform: time
    at: '06:00:00'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.ac_1b521f6_3

- id: 'automation_plantlights_off'
  alias: PlantLightsOff
  initial_state: true
  trigger:
    platform: time
    at: '22:00:00'
  action:
  - service: switch.turn_off
    data:
      entity_id:
      - switch.switch.ac_1b521f6_3
      - switch.plant_heatbed

- id: 'automation_plantheatbed'
  alias: ToggleHeatbed
  description: ''
  trigger:
  - platform: time_pattern
    minutes: '/15'
    seconds: 0
  condition:
    condition: time
    after: '06:00:00'
    before: '21:55:00'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.plant_heatbed
  - delay: "00:{{ '%02i'%states.input_select.heatbed_delay.state | int }}:00"
  - service: switch.turn_off
    data:
      entity_id: switch.plant_heatbed

##################################################################################
# Scripts
##################################################################################

